### PR TITLE
Implement new design

### PR DESCRIPTION
**Pull request by chrishrmnn**
This PR updates the browser extension:
- Update the design to fit the new Domain Search design in the dashboard: search results, email finder, errors/empty states
- Sunset the Author Finder

### CODE REVIEW

**Comment by chrishrmnn** [comment]
@fgrante PR is ready to review! 🚀

**Comment by fgrante** [comment]
Great job, Chris! I'm starting to test. There are a few things to fix, but overall, I think we are close!

The elements on the right of the head bar could be improved:

- The link "see results for ..." should not include the space and bullet
- Each element should have slightly larger horizontal margins
- Now that we have the connected avatar displayed, we can make it a link to `https://hunter.io/users/edit`

Monosnap 2023-02-06 09-12-08

Other UX/design issues:

- The "IT" and "HR" departments should be in capital letters.
- I'm not convinced by the loading state that displays the black bar at the bottom. It attracts the eye but we don't have the time to see what's inside. I think it would be better to have just the light "loading placeholder" (I forgot the name). Then the content is displayed only when the request is made.
- When we click on a label to select a checkbox in a filter (instead of the checkbox itself), the dropdown closes. Any click on a label should prevent the closing. 
- There a double dotted border below the patter abbreviations. The reason is that there is a default browser style with `abbr` with `text-decoration: underline dotted;`, on the top of our `border-bottom`. We have to pick one of the two!

Monosnap 2023-02-06 09-24-02

**Comment by chrishrmnn** [comment]
@fgrante Thanks for the feedback! Everything is managed.

Can you take care of the merge with `master`? It will be easier for you because you have pushed the latest changes.

**Review by fgrante — APPROVED** [review]

**Comment by fgrante** [comment]
Ready to go! I'm submitting it to the stores today.

**Pull request merged**
