### PR TITLE
Localize the extensions

### PR DESCRIPTION
**Pull request by fgrante**
This PR adds the ability to provide the browser extensions in several languages and introduces the translation to French.

It uses the i18n API, available in Chrome, Firefox, and Edge: https://developer.chrome.com/docs/extensions/reference/i18n/

Here is how to test by changing the language: https://developer.chrome.com/docs/extensions/reference/i18n/#how-to-set-browsers-locale

### CODE REVIEW

**Comment by chrishrmnn** [comment]
I don't know if I am missing something, but I can't load the French version:
- the version of the extension is 3.1.2
- my Chrome is in French
- my Hunter account is in French (not sure if it's required by I tried)
- I have errors in the Extension:
image

Do you think it's related to the errors?

**Comment by fgrante** [comment]
This error is something else unrelated, it should not be blocking. On my side, I had to change the language of my Mac and reboot to have the language switch.

**Comment by chrishrmnn** [comment]
My Mac and Chrome are in French by default. I give a try to restart, but the Extension is still in English 😖

I just realized that there is no French translation file in the`_locales/` folder, only the `en` file. Is that expected?

**Comment by fgrante** [comment]
Oh, my bad! The last commit didn't pass! You can try again. All my apologies.

**Review by chrishrmnn — APPROVED** [review]
I updated some translations to be aligned with the website.

I also make small updates to the filters dropdown: make sure the department names fit in one line in the dropdown, add a max-height to options (with a scroll if needed) to ensure the "Apply" button is always in the "viewport."

**Comment by fgrante** [comment]
Awesome! Thank you, Chris!

**Pull request merged**
